RUN apt update && apt-get install -y \
    texlive-latex-base \
    texlive-latex-extra \
    texlive-lang-european \
    texlive-bibtex-extra \
    biber \
    git \
    texstudio \
    jabref \
    r-base \
    texlive-xetex \
    texlive-fonts-recommended \
    fonts-bera \    
    python3-pip \
    latexmk \
    && pip install pygments \
    && rm -rf /var/lib/apt/lists/*
